/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author redst
 */
public class JCadUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form JCadUsuarios
     */
    public JCadUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel93 = new javax.swing.JPanel();
        jPanel94 = new javax.swing.JPanel();
        txtKcritico46 = new javax.swing.JTextField();
        jLKc46 = new javax.swing.JLabel();
        txtNomeMaterial46 = new javax.swing.JTextField();
        jLMaterial46 = new javax.swing.JLabel();
        jLEspessura46 = new javax.swing.JLabel();
        txtEspessura46 = new javax.swing.JTextField();
        jLargura46 = new javax.swing.JLabel();
        txtLargura46 = new javax.swing.JTextField();
        jScrollPane47 = new javax.swing.JScrollPane();
        jTabMateriais46 = new javax.swing.JTable();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jPanel95 = new javax.swing.JPanel();
        jButton141 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel93.setMaximumSize(new java.awt.Dimension(960, 540));
        jPanel93.setMinimumSize(new java.awt.Dimension(960, 540));
        jPanel93.setPreferredSize(new java.awt.Dimension(960, 540));

        jPanel94.setBackground(new java.awt.Color(153, 153, 153));
        jPanel94.setMaximumSize(new java.awt.Dimension(960, 540));
        jPanel94.setMinimumSize(new java.awt.Dimension(960, 540));
        jPanel94.setPreferredSize(new java.awt.Dimension(960, 540));

        txtKcritico46.setBackground(new java.awt.Color(188, 188, 188));

        jLKc46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLKc46.setForeground(new java.awt.Color(255, 255, 255));
        jLKc46.setText("Login:");

        txtNomeMaterial46.setBackground(new java.awt.Color(188, 188, 188));
        txtNomeMaterial46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMaterial46ActionPerformed(evt);
            }
        });

        jLMaterial46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLMaterial46.setForeground(new java.awt.Color(255, 255, 255));
        jLMaterial46.setText("Nome:");

        jLEspessura46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLEspessura46.setForeground(new java.awt.Color(255, 255, 255));
        jLEspessura46.setText("Senha:");

        txtEspessura46.setBackground(new java.awt.Color(188, 188, 188));
        txtEspessura46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspessura46ActionPerformed(evt);
            }
        });

        jLargura46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLargura46.setForeground(new java.awt.Color(255, 255, 255));
        jLargura46.setText("Formação:");

        txtLargura46.setBackground(new java.awt.Color(188, 188, 188));
        txtLargura46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLargura46ActionPerformed(evt);
            }
        });

        jTabMateriais46.setAutoCreateRowSorter(true);
        jTabMateriais46.setBackground(new java.awt.Color(204, 204, 204));
        jTabMateriais46.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Formação", "Login"
            }
        ));
        jTabMateriais46.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane47.setViewportView(jTabMateriais46);

        jButton139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/IcCadastrar_1.png"))); // NOI18N
        jButton139.setMaximumSize(new java.awt.Dimension(141, 27));
        jButton139.setMinimumSize(new java.awt.Dimension(141, 27));
        jButton139.setPreferredSize(new java.awt.Dimension(141, 27));
        jButton139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton139ActionPerformed(evt);
            }
        });

        jButton140.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/IcAtualizar.png"))); // NOI18N
        jButton140.setMaximumSize(new java.awt.Dimension(141, 27));
        jButton140.setMinimumSize(new java.awt.Dimension(141, 27));
        jButton140.setPreferredSize(new java.awt.Dimension(141, 27));
        jButton140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton140ActionPerformed(evt);
            }
        });

        jPanel95.setBackground(new java.awt.Color(94, 94, 94));
        jPanel95.setMaximumSize(new java.awt.Dimension(960, 76));
        jPanel95.setMinimumSize(new java.awt.Dimension(960, 76));

        jButton141.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/IcVoltar.png"))); // NOI18N
        jButton141.setMaximumSize(new java.awt.Dimension(143, 141));
        jButton141.setMinimumSize(new java.awt.Dimension(143, 141));
        jButton141.setPreferredSize(new java.awt.Dimension(143, 141));
        jButton141.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton141ActionPerformed(evt);
            }
        });

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/Titulo_Usuarios.png"))); // NOI18N
        jLabel47.setMaximumSize(new java.awt.Dimension(264, 76));
        jLabel47.setMinimumSize(new java.awt.Dimension(264, 76));
        jLabel47.setPreferredSize(new java.awt.Dimension(264, 76));

        javax.swing.GroupLayout jPanel95Layout = new javax.swing.GroupLayout(jPanel95);
        jPanel95.setLayout(jPanel95Layout);
        jPanel95Layout.setHorizontalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel95Layout.createSequentialGroup()
                .addComponent(jButton141, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 370, Short.MAX_VALUE))
        );
        jPanel95Layout.setVerticalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel95Layout.createSequentialGroup()
                .addGroup(jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton141, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel94Layout = new javax.swing.GroupLayout(jPanel94);
        jPanel94.setLayout(jPanel94Layout);
        jPanel94Layout.setHorizontalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel94Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel94Layout.createSequentialGroup()
                        .addComponent(jLargura46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLargura46, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLEspessura46)
                        .addGap(18, 18, 18)
                        .addComponent(txtEspessura46, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton140, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton139, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel94Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLMaterial46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeMaterial46, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLKc46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKcritico46, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jPanel95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel94Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel94Layout.setVerticalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel94Layout.createSequentialGroup()
                .addComponent(jPanel95, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMaterial46)
                    .addComponent(txtNomeMaterial46, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLKc46)
                    .addComponent(txtKcritico46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel94Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(txtEspessura46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLargura46)
                            .addComponent(txtLargura46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEspessura46)))
                    .addComponent(jButton140, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton139, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel93Layout = new javax.swing.GroupLayout(jPanel93);
        jPanel93.setLayout(jPanel93Layout);
        jPanel93Layout.setHorizontalGroup(
            jPanel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel93Layout.setVerticalGroup(
            jPanel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeMaterial46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMaterial46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMaterial46ActionPerformed

    private void txtEspessura46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspessura46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspessura46ActionPerformed

    private void txtLargura46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLargura46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargura46ActionPerformed

    private void jButton139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton139ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton139ActionPerformed

    private void jButton140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton140ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton140ActionPerformed

    private void jButton141ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton141ActionPerformed
        JMenu obj = new JMenu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton141ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCadUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCadUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLEspessura;
    private javax.swing.JLabel jLEspessura1;
    private javax.swing.JLabel jLEspessura10;
    private javax.swing.JLabel jLEspessura11;
    private javax.swing.JLabel jLEspessura12;
    private javax.swing.JLabel jLEspessura13;
    private javax.swing.JLabel jLEspessura14;
    private javax.swing.JLabel jLEspessura15;
    private javax.swing.JLabel jLEspessura16;
    private javax.swing.JLabel jLEspessura17;
    private javax.swing.JLabel jLEspessura18;
    private javax.swing.JLabel jLEspessura19;
    private javax.swing.JLabel jLEspessura2;
    private javax.swing.JLabel jLEspessura20;
    private javax.swing.JLabel jLEspessura21;
    private javax.swing.JLabel jLEspessura22;
    private javax.swing.JLabel jLEspessura23;
    private javax.swing.JLabel jLEspessura24;
    private javax.swing.JLabel jLEspessura25;
    private javax.swing.JLabel jLEspessura26;
    private javax.swing.JLabel jLEspessura27;
    private javax.swing.JLabel jLEspessura28;
    private javax.swing.JLabel jLEspessura29;
    private javax.swing.JLabel jLEspessura3;
    private javax.swing.JLabel jLEspessura30;
    private javax.swing.JLabel jLEspessura31;
    private javax.swing.JLabel jLEspessura32;
    private javax.swing.JLabel jLEspessura33;
    private javax.swing.JLabel jLEspessura34;
    private javax.swing.JLabel jLEspessura35;
    private javax.swing.JLabel jLEspessura36;
    private javax.swing.JLabel jLEspessura37;
    private javax.swing.JLabel jLEspessura38;
    private javax.swing.JLabel jLEspessura39;
    private javax.swing.JLabel jLEspessura4;
    private javax.swing.JLabel jLEspessura40;
    private javax.swing.JLabel jLEspessura41;
    private javax.swing.JLabel jLEspessura42;
    private javax.swing.JLabel jLEspessura43;
    private javax.swing.JLabel jLEspessura44;
    private javax.swing.JLabel jLEspessura45;
    private javax.swing.JLabel jLEspessura46;
    private javax.swing.JLabel jLEspessura5;
    private javax.swing.JLabel jLEspessura6;
    private javax.swing.JLabel jLEspessura7;
    private javax.swing.JLabel jLEspessura8;
    private javax.swing.JLabel jLEspessura9;
    private javax.swing.JLabel jLKc;
    private javax.swing.JLabel jLKc1;
    private javax.swing.JLabel jLKc10;
    private javax.swing.JLabel jLKc11;
    private javax.swing.JLabel jLKc12;
    private javax.swing.JLabel jLKc13;
    private javax.swing.JLabel jLKc14;
    private javax.swing.JLabel jLKc15;
    private javax.swing.JLabel jLKc16;
    private javax.swing.JLabel jLKc17;
    private javax.swing.JLabel jLKc18;
    private javax.swing.JLabel jLKc19;
    private javax.swing.JLabel jLKc2;
    private javax.swing.JLabel jLKc20;
    private javax.swing.JLabel jLKc21;
    private javax.swing.JLabel jLKc22;
    private javax.swing.JLabel jLKc23;
    private javax.swing.JLabel jLKc24;
    private javax.swing.JLabel jLKc25;
    private javax.swing.JLabel jLKc26;
    private javax.swing.JLabel jLKc27;
    private javax.swing.JLabel jLKc28;
    private javax.swing.JLabel jLKc29;
    private javax.swing.JLabel jLKc3;
    private javax.swing.JLabel jLKc30;
    private javax.swing.JLabel jLKc31;
    private javax.swing.JLabel jLKc32;
    private javax.swing.JLabel jLKc33;
    private javax.swing.JLabel jLKc34;
    private javax.swing.JLabel jLKc35;
    private javax.swing.JLabel jLKc36;
    private javax.swing.JLabel jLKc37;
    private javax.swing.JLabel jLKc38;
    private javax.swing.JLabel jLKc39;
    private javax.swing.JLabel jLKc4;
    private javax.swing.JLabel jLKc40;
    private javax.swing.JLabel jLKc41;
    private javax.swing.JLabel jLKc42;
    private javax.swing.JLabel jLKc43;
    private javax.swing.JLabel jLKc44;
    private javax.swing.JLabel jLKc45;
    private javax.swing.JLabel jLKc46;
    private javax.swing.JLabel jLKc5;
    private javax.swing.JLabel jLKc6;
    private javax.swing.JLabel jLKc7;
    private javax.swing.JLabel jLKc8;
    private javax.swing.JLabel jLKc9;
    private javax.swing.JLabel jLMaterial;
    private javax.swing.JLabel jLMaterial1;
    private javax.swing.JLabel jLMaterial10;
    private javax.swing.JLabel jLMaterial11;
    private javax.swing.JLabel jLMaterial12;
    private javax.swing.JLabel jLMaterial13;
    private javax.swing.JLabel jLMaterial14;
    private javax.swing.JLabel jLMaterial15;
    private javax.swing.JLabel jLMaterial16;
    private javax.swing.JLabel jLMaterial17;
    private javax.swing.JLabel jLMaterial18;
    private javax.swing.JLabel jLMaterial19;
    private javax.swing.JLabel jLMaterial2;
    private javax.swing.JLabel jLMaterial20;
    private javax.swing.JLabel jLMaterial21;
    private javax.swing.JLabel jLMaterial22;
    private javax.swing.JLabel jLMaterial23;
    private javax.swing.JLabel jLMaterial24;
    private javax.swing.JLabel jLMaterial25;
    private javax.swing.JLabel jLMaterial26;
    private javax.swing.JLabel jLMaterial27;
    private javax.swing.JLabel jLMaterial28;
    private javax.swing.JLabel jLMaterial29;
    private javax.swing.JLabel jLMaterial3;
    private javax.swing.JLabel jLMaterial30;
    private javax.swing.JLabel jLMaterial31;
    private javax.swing.JLabel jLMaterial32;
    private javax.swing.JLabel jLMaterial33;
    private javax.swing.JLabel jLMaterial34;
    private javax.swing.JLabel jLMaterial35;
    private javax.swing.JLabel jLMaterial36;
    private javax.swing.JLabel jLMaterial37;
    private javax.swing.JLabel jLMaterial38;
    private javax.swing.JLabel jLMaterial39;
    private javax.swing.JLabel jLMaterial4;
    private javax.swing.JLabel jLMaterial40;
    private javax.swing.JLabel jLMaterial41;
    private javax.swing.JLabel jLMaterial42;
    private javax.swing.JLabel jLMaterial43;
    private javax.swing.JLabel jLMaterial44;
    private javax.swing.JLabel jLMaterial45;
    private javax.swing.JLabel jLMaterial46;
    private javax.swing.JLabel jLMaterial5;
    private javax.swing.JLabel jLMaterial6;
    private javax.swing.JLabel jLMaterial7;
    private javax.swing.JLabel jLMaterial8;
    private javax.swing.JLabel jLMaterial9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLargura;
    private javax.swing.JLabel jLargura1;
    private javax.swing.JLabel jLargura10;
    private javax.swing.JLabel jLargura11;
    private javax.swing.JLabel jLargura12;
    private javax.swing.JLabel jLargura13;
    private javax.swing.JLabel jLargura14;
    private javax.swing.JLabel jLargura15;
    private javax.swing.JLabel jLargura16;
    private javax.swing.JLabel jLargura17;
    private javax.swing.JLabel jLargura18;
    private javax.swing.JLabel jLargura19;
    private javax.swing.JLabel jLargura2;
    private javax.swing.JLabel jLargura20;
    private javax.swing.JLabel jLargura21;
    private javax.swing.JLabel jLargura22;
    private javax.swing.JLabel jLargura23;
    private javax.swing.JLabel jLargura24;
    private javax.swing.JLabel jLargura25;
    private javax.swing.JLabel jLargura26;
    private javax.swing.JLabel jLargura27;
    private javax.swing.JLabel jLargura28;
    private javax.swing.JLabel jLargura29;
    private javax.swing.JLabel jLargura3;
    private javax.swing.JLabel jLargura30;
    private javax.swing.JLabel jLargura31;
    private javax.swing.JLabel jLargura32;
    private javax.swing.JLabel jLargura33;
    private javax.swing.JLabel jLargura34;
    private javax.swing.JLabel jLargura35;
    private javax.swing.JLabel jLargura36;
    private javax.swing.JLabel jLargura37;
    private javax.swing.JLabel jLargura38;
    private javax.swing.JLabel jLargura39;
    private javax.swing.JLabel jLargura4;
    private javax.swing.JLabel jLargura40;
    private javax.swing.JLabel jLargura41;
    private javax.swing.JLabel jLargura42;
    private javax.swing.JLabel jLargura43;
    private javax.swing.JLabel jLargura44;
    private javax.swing.JLabel jLargura45;
    private javax.swing.JLabel jLargura46;
    private javax.swing.JLabel jLargura5;
    private javax.swing.JLabel jLargura6;
    private javax.swing.JLabel jLargura7;
    private javax.swing.JLabel jLargura8;
    private javax.swing.JLabel jLargura9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel88;
    private javax.swing.JPanel jPanel89;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTabMateriais;
    private javax.swing.JTable jTabMateriais1;
    private javax.swing.JTable jTabMateriais10;
    private javax.swing.JTable jTabMateriais11;
    private javax.swing.JTable jTabMateriais12;
    private javax.swing.JTable jTabMateriais13;
    private javax.swing.JTable jTabMateriais14;
    private javax.swing.JTable jTabMateriais15;
    private javax.swing.JTable jTabMateriais16;
    private javax.swing.JTable jTabMateriais17;
    private javax.swing.JTable jTabMateriais18;
    private javax.swing.JTable jTabMateriais19;
    private javax.swing.JTable jTabMateriais2;
    private javax.swing.JTable jTabMateriais20;
    private javax.swing.JTable jTabMateriais21;
    private javax.swing.JTable jTabMateriais22;
    private javax.swing.JTable jTabMateriais23;
    private javax.swing.JTable jTabMateriais24;
    private javax.swing.JTable jTabMateriais25;
    private javax.swing.JTable jTabMateriais26;
    private javax.swing.JTable jTabMateriais27;
    private javax.swing.JTable jTabMateriais28;
    private javax.swing.JTable jTabMateriais29;
    private javax.swing.JTable jTabMateriais3;
    private javax.swing.JTable jTabMateriais30;
    private javax.swing.JTable jTabMateriais31;
    private javax.swing.JTable jTabMateriais32;
    private javax.swing.JTable jTabMateriais33;
    private javax.swing.JTable jTabMateriais34;
    private javax.swing.JTable jTabMateriais35;
    private javax.swing.JTable jTabMateriais36;
    private javax.swing.JTable jTabMateriais37;
    private javax.swing.JTable jTabMateriais38;
    private javax.swing.JTable jTabMateriais39;
    private javax.swing.JTable jTabMateriais4;
    private javax.swing.JTable jTabMateriais40;
    private javax.swing.JTable jTabMateriais41;
    private javax.swing.JTable jTabMateriais42;
    private javax.swing.JTable jTabMateriais43;
    private javax.swing.JTable jTabMateriais44;
    private javax.swing.JTable jTabMateriais45;
    private javax.swing.JTable jTabMateriais46;
    private javax.swing.JTable jTabMateriais5;
    private javax.swing.JTable jTabMateriais6;
    private javax.swing.JTable jTabMateriais7;
    private javax.swing.JTable jTabMateriais8;
    private javax.swing.JTable jTabMateriais9;
    private javax.swing.JTextField txtEspessura;
    private javax.swing.JTextField txtEspessura1;
    private javax.swing.JTextField txtEspessura10;
    private javax.swing.JTextField txtEspessura11;
    private javax.swing.JTextField txtEspessura12;
    private javax.swing.JTextField txtEspessura13;
    private javax.swing.JTextField txtEspessura14;
    private javax.swing.JTextField txtEspessura15;
    private javax.swing.JTextField txtEspessura16;
    private javax.swing.JTextField txtEspessura17;
    private javax.swing.JTextField txtEspessura18;
    private javax.swing.JTextField txtEspessura19;
    private javax.swing.JTextField txtEspessura2;
    private javax.swing.JTextField txtEspessura20;
    private javax.swing.JTextField txtEspessura21;
    private javax.swing.JTextField txtEspessura22;
    private javax.swing.JTextField txtEspessura23;
    private javax.swing.JTextField txtEspessura24;
    private javax.swing.JTextField txtEspessura25;
    private javax.swing.JTextField txtEspessura26;
    private javax.swing.JTextField txtEspessura27;
    private javax.swing.JTextField txtEspessura28;
    private javax.swing.JTextField txtEspessura29;
    private javax.swing.JTextField txtEspessura3;
    private javax.swing.JTextField txtEspessura30;
    private javax.swing.JTextField txtEspessura31;
    private javax.swing.JTextField txtEspessura32;
    private javax.swing.JTextField txtEspessura33;
    private javax.swing.JTextField txtEspessura34;
    private javax.swing.JTextField txtEspessura35;
    private javax.swing.JTextField txtEspessura36;
    private javax.swing.JTextField txtEspessura37;
    private javax.swing.JTextField txtEspessura38;
    private javax.swing.JTextField txtEspessura39;
    private javax.swing.JTextField txtEspessura4;
    private javax.swing.JTextField txtEspessura40;
    private javax.swing.JTextField txtEspessura41;
    private javax.swing.JTextField txtEspessura42;
    private javax.swing.JTextField txtEspessura43;
    private javax.swing.JTextField txtEspessura44;
    private javax.swing.JTextField txtEspessura45;
    private javax.swing.JTextField txtEspessura46;
    private javax.swing.JTextField txtEspessura5;
    private javax.swing.JTextField txtEspessura6;
    private javax.swing.JTextField txtEspessura7;
    private javax.swing.JTextField txtEspessura8;
    private javax.swing.JTextField txtEspessura9;
    private javax.swing.JTextField txtKcritico;
    private javax.swing.JTextField txtKcritico1;
    private javax.swing.JTextField txtKcritico10;
    private javax.swing.JTextField txtKcritico11;
    private javax.swing.JTextField txtKcritico12;
    private javax.swing.JTextField txtKcritico13;
    private javax.swing.JTextField txtKcritico14;
    private javax.swing.JTextField txtKcritico15;
    private javax.swing.JTextField txtKcritico16;
    private javax.swing.JTextField txtKcritico17;
    private javax.swing.JTextField txtKcritico18;
    private javax.swing.JTextField txtKcritico19;
    private javax.swing.JTextField txtKcritico2;
    private javax.swing.JTextField txtKcritico20;
    private javax.swing.JTextField txtKcritico21;
    private javax.swing.JTextField txtKcritico22;
    private javax.swing.JTextField txtKcritico23;
    private javax.swing.JTextField txtKcritico24;
    private javax.swing.JTextField txtKcritico25;
    private javax.swing.JTextField txtKcritico26;
    private javax.swing.JTextField txtKcritico27;
    private javax.swing.JTextField txtKcritico28;
    private javax.swing.JTextField txtKcritico29;
    private javax.swing.JTextField txtKcritico3;
    private javax.swing.JTextField txtKcritico30;
    private javax.swing.JTextField txtKcritico31;
    private javax.swing.JTextField txtKcritico32;
    private javax.swing.JTextField txtKcritico33;
    private javax.swing.JTextField txtKcritico34;
    private javax.swing.JTextField txtKcritico35;
    private javax.swing.JTextField txtKcritico36;
    private javax.swing.JTextField txtKcritico37;
    private javax.swing.JTextField txtKcritico38;
    private javax.swing.JTextField txtKcritico39;
    private javax.swing.JTextField txtKcritico4;
    private javax.swing.JTextField txtKcritico40;
    private javax.swing.JTextField txtKcritico41;
    private javax.swing.JTextField txtKcritico42;
    private javax.swing.JTextField txtKcritico43;
    private javax.swing.JTextField txtKcritico44;
    private javax.swing.JTextField txtKcritico45;
    private javax.swing.JTextField txtKcritico46;
    private javax.swing.JTextField txtKcritico5;
    private javax.swing.JTextField txtKcritico6;
    private javax.swing.JTextField txtKcritico7;
    private javax.swing.JTextField txtKcritico8;
    private javax.swing.JTextField txtKcritico9;
    private javax.swing.JTextField txtLargura;
    private javax.swing.JTextField txtLargura1;
    private javax.swing.JTextField txtLargura10;
    private javax.swing.JTextField txtLargura11;
    private javax.swing.JTextField txtLargura12;
    private javax.swing.JTextField txtLargura13;
    private javax.swing.JTextField txtLargura14;
    private javax.swing.JTextField txtLargura15;
    private javax.swing.JTextField txtLargura16;
    private javax.swing.JTextField txtLargura17;
    private javax.swing.JTextField txtLargura18;
    private javax.swing.JTextField txtLargura19;
    private javax.swing.JTextField txtLargura2;
    private javax.swing.JTextField txtLargura20;
    private javax.swing.JTextField txtLargura21;
    private javax.swing.JTextField txtLargura22;
    private javax.swing.JTextField txtLargura23;
    private javax.swing.JTextField txtLargura24;
    private javax.swing.JTextField txtLargura25;
    private javax.swing.JTextField txtLargura26;
    private javax.swing.JTextField txtLargura27;
    private javax.swing.JTextField txtLargura28;
    private javax.swing.JTextField txtLargura29;
    private javax.swing.JTextField txtLargura3;
    private javax.swing.JTextField txtLargura30;
    private javax.swing.JTextField txtLargura31;
    private javax.swing.JTextField txtLargura32;
    private javax.swing.JTextField txtLargura33;
    private javax.swing.JTextField txtLargura34;
    private javax.swing.JTextField txtLargura35;
    private javax.swing.JTextField txtLargura36;
    private javax.swing.JTextField txtLargura37;
    private javax.swing.JTextField txtLargura38;
    private javax.swing.JTextField txtLargura39;
    private javax.swing.JTextField txtLargura4;
    private javax.swing.JTextField txtLargura40;
    private javax.swing.JTextField txtLargura41;
    private javax.swing.JTextField txtLargura42;
    private javax.swing.JTextField txtLargura43;
    private javax.swing.JTextField txtLargura44;
    private javax.swing.JTextField txtLargura45;
    private javax.swing.JTextField txtLargura46;
    private javax.swing.JTextField txtLargura5;
    private javax.swing.JTextField txtLargura6;
    private javax.swing.JTextField txtLargura7;
    private javax.swing.JTextField txtLargura8;
    private javax.swing.JTextField txtLargura9;
    private javax.swing.JTextField txtNomeMaterial;
    private javax.swing.JTextField txtNomeMaterial1;
    private javax.swing.JTextField txtNomeMaterial10;
    private javax.swing.JTextField txtNomeMaterial11;
    private javax.swing.JTextField txtNomeMaterial12;
    private javax.swing.JTextField txtNomeMaterial13;
    private javax.swing.JTextField txtNomeMaterial14;
    private javax.swing.JTextField txtNomeMaterial15;
    private javax.swing.JTextField txtNomeMaterial16;
    private javax.swing.JTextField txtNomeMaterial17;
    private javax.swing.JTextField txtNomeMaterial18;
    private javax.swing.JTextField txtNomeMaterial19;
    private javax.swing.JTextField txtNomeMaterial2;
    private javax.swing.JTextField txtNomeMaterial20;
    private javax.swing.JTextField txtNomeMaterial21;
    private javax.swing.JTextField txtNomeMaterial22;
    private javax.swing.JTextField txtNomeMaterial23;
    private javax.swing.JTextField txtNomeMaterial24;
    private javax.swing.JTextField txtNomeMaterial25;
    private javax.swing.JTextField txtNomeMaterial26;
    private javax.swing.JTextField txtNomeMaterial27;
    private javax.swing.JTextField txtNomeMaterial28;
    private javax.swing.JTextField txtNomeMaterial29;
    private javax.swing.JTextField txtNomeMaterial3;
    private javax.swing.JTextField txtNomeMaterial30;
    private javax.swing.JTextField txtNomeMaterial31;
    private javax.swing.JTextField txtNomeMaterial32;
    private javax.swing.JTextField txtNomeMaterial33;
    private javax.swing.JTextField txtNomeMaterial34;
    private javax.swing.JTextField txtNomeMaterial35;
    private javax.swing.JTextField txtNomeMaterial36;
    private javax.swing.JTextField txtNomeMaterial37;
    private javax.swing.JTextField txtNomeMaterial38;
    private javax.swing.JTextField txtNomeMaterial39;
    private javax.swing.JTextField txtNomeMaterial4;
    private javax.swing.JTextField txtNomeMaterial40;
    private javax.swing.JTextField txtNomeMaterial41;
    private javax.swing.JTextField txtNomeMaterial42;
    private javax.swing.JTextField txtNomeMaterial43;
    private javax.swing.JTextField txtNomeMaterial44;
    private javax.swing.JTextField txtNomeMaterial45;
    private javax.swing.JTextField txtNomeMaterial46;
    private javax.swing.JTextField txtNomeMaterial5;
    private javax.swing.JTextField txtNomeMaterial6;
    private javax.swing.JTextField txtNomeMaterial7;
    private javax.swing.JTextField txtNomeMaterial8;
    private javax.swing.JTextField txtNomeMaterial9;
    // End of variables declaration//GEN-END:variables
}
