/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author redst
 */
public class JMenu extends javax.swing.JFrame {

    /**
     * Creates new form JMenu
     */
    public JMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtKcritico = new javax.swing.JTextField();
        jLKc = new javax.swing.JLabel();
        txtNomeMaterial = new javax.swing.JTextField();
        jLMaterial = new javax.swing.JLabel();
        jLEspessura = new javax.swing.JLabel();
        txtEspessura = new javax.swing.JTextField();
        txtCMax = new javax.swing.JTextField();
        jCMax = new javax.swing.JLabel();
        jLargura = new javax.swing.JLabel();
        txtLargura = new javax.swing.JTextField();
        txtCMin = new javax.swing.JTextField();
        jLCMin = new javax.swing.JLabel();
        jBCVLN = new javax.swing.JButton();
        jBCVLog = new javax.swing.JButton();
        jBImportTxt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 540));

        txtKcritico.setBackground(new java.awt.Color(188, 188, 188));

        jLKc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLKc.setForeground(new java.awt.Color(255, 255, 255));
        jLKc.setText("Kc:");

        txtNomeMaterial.setBackground(new java.awt.Color(188, 188, 188));
        txtNomeMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMaterialActionPerformed(evt);
            }
        });

        jLMaterial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLMaterial.setForeground(new java.awt.Color(255, 255, 255));
        jLMaterial.setText("Material:");

        jLEspessura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLEspessura.setForeground(new java.awt.Color(255, 255, 255));
        jLEspessura.setText("Espessura:");

        txtEspessura.setBackground(new java.awt.Color(188, 188, 188));
        txtEspessura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspessuraActionPerformed(evt);
            }
        });

        txtCMax.setBackground(new java.awt.Color(188, 188, 188));
        txtCMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMaxActionPerformed(evt);
            }
        });

        jCMax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCMax.setForeground(new java.awt.Color(255, 255, 255));
        jCMax.setText("Carregamento Max:");

        jLargura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLargura.setForeground(new java.awt.Color(255, 255, 255));
        jLargura.setText("Largura:");

        txtLargura.setBackground(new java.awt.Color(188, 188, 188));
        txtLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLarguraActionPerformed(evt);
            }
        });

        txtCMin.setBackground(new java.awt.Color(188, 188, 188));
        txtCMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMinActionPerformed(evt);
            }
        });

        jLCMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLCMin.setForeground(new java.awt.Color(255, 255, 255));
        jLCMin.setText("Carregamento Min:");

        jBCVLN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/IcCurvaLxN.png"))); // NOI18N
        jBCVLN.setMaximumSize(new java.awt.Dimension(141, 27));
        jBCVLN.setMinimumSize(new java.awt.Dimension(141, 27));
        jBCVLN.setPreferredSize(new java.awt.Dimension(141, 27));
        jBCVLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCVLNActionPerformed(evt);
            }
        });

        jBCVLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/IcCurvaLog.png"))); // NOI18N
        jBCVLog.setMaximumSize(new java.awt.Dimension(141, 27));
        jBCVLog.setMinimumSize(new java.awt.Dimension(141, 27));
        jBCVLog.setPreferredSize(new java.awt.Dimension(141, 27));

        jBImportTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/IcImportarTxT.png"))); // NOI18N
        jBImportTxt.setMaximumSize(new java.awt.Dimension(141, 27));
        jBImportTxt.setMinimumSize(new java.awt.Dimension(141, 27));
        jBImportTxt.setPreferredSize(new java.awt.Dimension(141, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLargura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNomeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLKc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKcritico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtLargura)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLEspessura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jBCVLN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLCMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCMin, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCMax, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBCVLog, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBImportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMaterial)
                    .addComponent(txtNomeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKcritico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLKc)
                    .addComponent(jCMax)
                    .addComponent(txtCMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLargura)
                        .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCMin)
                        .addComponent(txtCMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLEspessura)
                        .addComponent(txtEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jBCVLN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jBCVLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jBImportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 211, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 211, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(56, 62));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 62));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 62));

        jMenu3.setText("Cadastro");
        jMenu3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Materiais");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setBackground(new java.awt.Color(0, 211, 255));
        jMenu2.setText("Historico");
        jMenu2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Login");
        jMenu4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jMenu4.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu4MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu9.setText("Sobre");
        jMenu9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JCadMaterial obj = new JCadMaterial();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JCadUsuarios obj = new JCadUsuarios();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu4MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu4MenuKeyPressed

    }//GEN-LAST:event_jMenu4MenuKeyPressed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        JLogin obj = new JLogin();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        JLogin obj = new JLogin();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void txtNomeMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMaterialActionPerformed

    private void txtEspessuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspessuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspessuraActionPerformed

    private void txtCMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMaxActionPerformed

    private void txtLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLarguraActionPerformed

    private void txtCMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMinActionPerformed

    private void jBCVLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCVLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCVLNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCVLN;
    private javax.swing.JButton jBCVLog;
    private javax.swing.JButton jBImportTxt;
    private javax.swing.JLabel jCMax;
    private javax.swing.JLabel jLCMin;
    private javax.swing.JLabel jLEspessura;
    private javax.swing.JLabel jLKc;
    private javax.swing.JLabel jLMaterial;
    private javax.swing.JLabel jLargura;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCMax;
    private javax.swing.JTextField txtCMin;
    private javax.swing.JTextField txtEspessura;
    private javax.swing.JTextField txtKcritico;
    private javax.swing.JTextField txtLargura;
    private javax.swing.JTextField txtNomeMaterial;
    // End of variables declaration//GEN-END:variables
}
